#!/usr/bin/python

import re 
import sys

cents=r"\$?\.\d{2,3}"
dc=r"\$?\d{d,}(\.?(\d{2,3})?)?"
r=re.compile(r"{cents}|{dc}".format(cents=cents,dc=dc))
for l in sys.stdin.readlines():
    print l.rstrip(),
    if r.match(l) == None:
        print "faled"
    else:
        print "Yes" 



