#!/usr/bin/python

import wget
import matplotlib
import csv
import matplotlib.pyplot as plt

print('Starting Download of data')

url = 'http://courses.eece.maine.edu/ece331/data.csv'
wget.download(url, '/home/pi/Documents/ECE331/Programs/python/data.csv')

temperature=[]
date=[]

with open ('data.csv') as datafile:
	datafile=csv.reader(datafile,delimiter='	')
	next (datafile)

	for row in datafile:
		temperature.append(float(row [6]))	
		temp=[]

		for x in xrange(2):
			temp.append(row [x])

		date.append(temp)
temp2=[]
for y in range(72):
	temp2.append(y)

plt.ylabel('Temperature in degrees F')
plt.xlabel('Time')
plt.title('Temperature over time')
plt.semilogx(temp2,temperature)
plt.show()
